---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  # All tests specified in the `/plans/` subdir
  - job: tests
    trigger: pull_request
    skip_build: true
    #notifications:
     # failure_comment:
      #  message: "Tests failed."
    targets:
      - fedora-rawhide-x86_64
      - fedora-rawhide-aarch64
    tf_extra_params:
      environments:
        - os:
          - compose: null
